wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1635691605
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      - 16
      4: 3.8.8
      5: 0.12.4
      8:
      - 3
      - 5
method:
  desc: null
  value: random
metric:
  desc: null
  value:
    goal: minimize
    name: loss
parameters:
  desc: null
  value:
    batch_size:
      values:
      - 1
      - 6
      - 8
      - 16
    learning_rate:
      values:
      - 0.0001
      - 2.0e-05
      - 1.0e-05
      - 1.0e-07
    optimizer:
      values:
      - adam
      - sgd
